### ISSUE TITLE
Setting Dashboard Domain

### ISSUE THREAD

**Issue by Rojikku** [containous/traefik-helm-chart#119]
Was attempting to migrate from the stable 1.7 to the latest of this chart.

Where the heck did you guys put [this](https://github.com/helm/charts/blob/master/stable/traefik/values.yaml#L362)?

Everything else works fine, far as I can tell, but I want my dashboard domain!
How else am I supposed to access my dashboard? I literally can't find it, and it's defaulted to enabled.

Please put that config option back.

**Comment by ldez** [comment]
Hello,

If you want to define your how domain, we recommend to create a dedicated ingress route to that.

The dashboard in this chart is mainly for dev and testing purpose.
