### ISSUE TITLE
Upgrade to 2.2.0 with helm upgrade

### ISSUE THREAD

**Issue by myco** [containous/traefik-helm-chart#128]
Seems the problem still exists #95 
I'm trying to upgrade to 2.2.0 with command "helm upgrade"
and getting errors in container logs:
"Failed to list *v1alpha1.TLSStore: the server could not find the requested resource"

Does it mean 'helm upgrade' doesn't work correctly?

**Comment by mmatur** [comment]
Hi @myco,

From which version are you trying to upgrade?
What is your helm version?

**Comment by myco** [comment]
from version traefik-6.0.0   2.1.3
helm version v3.1.0

**Comment by mmatur** [comment]
@myco after some investigation seems to be an issue for other users too https://github.com/helm/helm/issues/7735.

This is a decision from helm when they introduce CRDs with this PR https://github.com/helm/helm/pull/6243
> CRDs are not upgraded during helm install or helm upgrade. There is no accepted practice for managing CRD upgrades (again, because they are a global resources, and an upgrade can break things in interesting ways), so we decided not to handle this case. It is up to the operator.

So you have to manage this CRDs manually during an upgrade.

**Comment by mmatur** [comment]
So I am closing this issue because this is not something we can handle here.

Thanks
