### ISSUE TITLE
Helm 2 is not supported anymore

### ISSUE THREAD

**Issue by volym3ad** [containous/traefik-helm-chart#136]
Due to `apiVersion: v2` in Chart.yaml Helm 2 isn't supported anymore. This change was made by pr https://github.com/containous/traefik-helm-chart/pull/94

Do you still support v2? If so, can you please change back apiVersion value. Charts supporting previous Helm versions have an apiVersion set to v1 and are still installable by Helm 3 (from official helm doc https://helm.sh/docs/topics/charts/ ).

**Comment by mmatur** [comment]
@volym3ad 

The way that CRDs are managed between helm 2 and helm 3 is completely different. So this is why for now we only support helm 3.

Only change back the `apiVersion` will not allow us to support helm 2. 

More investigation need to be done on this.

**Comment by volym3ad** [comment]
As far as I can see from readme you have to deploy CRDs manually in Helm 2. So that there is no need in chart customization for CRDs. Am I right?

**Comment by mmatur** [comment]
@volym3ad 

You are right. My bad. 
Thanks
A PR has been opened.
