### ISSUE TITLE
Be able to specify volumes and --configfile flag

### ISSUE THREAD

**Issue by frelon** [containous/traefik-helm-chart#14]
In order to be able to use custom config-file from a config-map or secret it would be nice to be able to specify volumes/volumeMounts for deployment resource and --configfile="" argument in deployment args.

**Comment by dtomcej** [comment]
Hello @frelon, Since you cannot combine a configfile and environment variable configuration or command line configurations, enabling this would require you to completely manually configure everything via the config file, and manually edit the deployment to match.

If that is your goal, then this helm chart will be of no use to you.

**Comment by dtomcej** [comment]
@frelon,

Our team is further discussing your proposal. We want to ensure that we have a clear direction before taking a decision on this one.

**Comment by frelon** [comment]
Aha, yes I was a little quick in the implementation... I also thought we would be able to do TLS termination+redirect like in traefik 1.6 (right in the endpoint) which was why I wanted to mount the config-file...

I also thought it would be nice to be able to do something like this:

```yaml
# values.yaml
...

config:
  path: /config/traefik-config.toml
  data: |
    # Traefik-config
    [log]
      level = "info"
    # ...
```

And have it create a config-map that is mounted automatically.

On the other hand we are going to try out [cert-manager](https://github.com/jetstack/cert-manager) so we don't need to specify a custom config for traefik.

Feel free to close this!

**Comment by sshishov** [comment]
Why we cannot merge CLI and EnvVars and configFIle? What is the problem here to have priority between them? Like if EnvVar is specified, use it, otherwise use CLI, otherwise use file. Or you can come up with proper priority to satisfy needs and Chart
