### ISSUE TITLE
Documentation / Confiuration Options

### ISSUE THREAD

**Issue by DanielHabenicht** [containous/traefik-helm-chart#149]
The v1 Chart had a table with all the configuration options.  [See here](https://github.com/helm/charts/tree/master/stable/traefik#configuration)

I couldn't find the same documentation for this chart. 

Is there one?

**Comment by mmatur** [comment]
@DanielHabenicht 

Thanks for your question.

The list of available options is available [here](https://github.com/containous/traefik-helm-chart/blob/master/traefik/values.yaml)

**Comment by DanielHabenicht** [comment]
That's all? 
The list for v1.x was way more extensive. But 2.x seems young so it's ok that there is not as much functionality as in v1. 

As soon as I find out how to configure let's encrypt with traefik and helm I will contribute :)

**Comment by mmatur** [comment]
@DanielHabenicht yes that's all and we haven't plan to add more things on it.

With fields available in the values.yaml you can configure all Traefik features. 

We have decided to have another approach to have something more generic and simplest to maintain in the long term.
