### ISSUE TITLE
Upgrading from version 7.2.0 to 8.0.2

### ISSUE THREAD

**Issue by rabberbock** [containous/traefik-helm-chart#153]
When I upgraded the helm chart from `7.2.0` I encountered the following error on the helm upgrade. 

```
client.go:404: Cannot patch Deployment: "traefik" (Deployment.apps "traefik" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"traefik", "app.kubernetes.io/instance":"traefik", "app.kubernetes.io/name":"traefik", "release":"traefik"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable)
```

I did not get a chance to look at it yet, but thought I would post now and post more details later. Any ideas for upgrading without having to delete the older release?

**Comment by notsureifkevin** [comment]
Ran into this as well while. It appears the `selector` field was made immutable after much discussion internally (ref: https://github.com/kubernetes/kubernetes/issues/50808) and while I didn't dig too far into the weeds on it, I didn't see a path forward to upgrade in place.

I'll be installing a completely new deployment today and re-configuring my ALB to forward traffic to the new ports.

**Comment by myco** [comment]
Just wondering if there is an upgrade check before new chart release appears. It would be nice, as on production systems it can be quite crucial.

**Comment by mmatur** [comment]
Folks,

Since #142, the labels has changed to follow helm best practices.

We have bump the major version of the chart so it means that it is a breaking change. 

The project follows semantic versioning.

I will close this issue because I think the question is answered.
