### ISSUE TITLE
[documentation] Could you add a deployment example please?

### ISSUE THREAD

**Issue by lakano** [containous/traefik-helm-chart#16]
Hello,
Thanks a lot for this helm Chart. 
I'm trying to replace our old traefik v1.x chart with this 2.0 without success.
Could you share a sample example of deployment of an application please?

**Comment by dtomcej** [comment]
Hello @lakano,

Please see the Kubernetes user guide here:

https://docs.traefik.io/v2.0/user-guides/crd-acme/#cluster-resources

**Comment by mmatur** [comment]
I am closing this PR because the question is answered.

**Comment by polRk** [comment]
Example doesn't use helm chart and helm chart values
