### ISSUE TITLE
http to https redirect without adding new entrypoints

### ISSUE THREAD

**Issue by SimonTheLeg** [containous/traefik-helm-chart#166]
hey guys,

is it possible to enforce a http to https redirect with the default two entrypoints?

I've tried to set the following in values.yml

```
additionalArguments:
  - --entrypoints.web.http.redirections.entrypoint.to=websecure
  - --entrypoints.web.http.redirections.entrypoint.permanent=true
```

But now if you try to access traefik from outside the cluster via http and `:80`, it re-directs to the value of websecure, which is `:8443`. This of course does not work, because the k8s service does the port remapping from `:443` to `:8443` and itself does not listen on `:8443`

**Is there a special setting in traefik to allow this with the default entrypoints?** Otherwise I guess I'll have to remove the securityContext and let traefik directly bind to :80 and :443, but this of course is not super nice.

**Comment by ldez** [comment]
Hello,

you can do that:

```
additionalArguments:
  - --entrypoints.web.http.redirections.entrypoint.to=:443
  - --entrypoints.web.http.redirections.entrypoint.permanent=true
```

**Comment by SimonTheLeg** [comment]
huh, the solution was right in front of my eyes 🙈
Works perfectly thanks a lot!

**Comment by ekarlso** [comment]
But is this option valid for Kubernetes Ingress as well as IngressRoutes to basically enable default redirets?

**Comment by mmatur** [comment]
@ekarlso yes

**Comment by ekarlso** [comment]
@mmatur I have enabled it but going towards a non-existant route gives a 302 while going towards a Kubernetes Ingress source provided route actually fowards the traffic to the service on plain http.

Both http and https actually work directly towards a given existing service though I would assume that it should have redirected me to https?

**Comment by mmatur** [comment]
@ekarlso Could you please open a discussion on the [community forum](https://community.containo.us) it will be a best place to discuss about your question.

**Comment by ekarlso** [comment]
@mmatur I already did but sadly it seems like a bug or how it works to me?
