### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by rxbn** [containous/traefik-helm-chart#167]
Hello Traefik :)

How can I configure the helm chart, so that Traefik redirects all http traffic to https?

Thanks!

**Comment by mmatur** [comment]
@rxbn Thanks for your question

You can solve this with the following values.yaml

```yaml
additionalArguments:
  - --entrypoints.web.http.redirections.entrypoint.to=:443
  - --entrypoints.web.http.redirections.entrypoint.permanent=true
```

Duplicate of #166
