### ISSUE TITLE
GKE LoadBalancerIP Use Case

### ISSUE THREAD

**Issue by stephenh1991** [containous/traefik-helm-chart#181]
Hi There! 

Firstly, love Traefik v2, huge improvement all round! 😄 

We use the chart in GKE and are trying to ensure we always receive the same IP address even if the k8s service gets recreated. Currently deploying the LB outside of GKE reduces a lot of the ease of use of the chart just to get a stable static IP.

I understand from the Contributing guide that you want to "avoid specific use cases" however i think GKE is a fairly broad use case and the `spec.loadBalancerIP: <YOUR IP HERE>` would be a useful addition.

Docs are here: https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip

I'm happy to contribute this myself as a conditional but wanted to see if you though this was useful before putting the work in?

Cheers,
Steve

**Comment by SantoDE** [comment]
Hello @stephenh1991,

this is already possible, isn't it? We have a value you can use to put that spec into the installation process.

Take a look at https://github.com/containous/traefik-helm-chart/blob/969b123bc8c2fe1e9f52e491f000b02a5b0cab61/traefik/values.yaml#L123

Does that work for you?

**Comment by stephenh1991** [comment]
@SantoDE Sorry, I totally missed that! Must be a Monday 🤦 

Yep that will do the trick! Sorry to waste your time 😅
