### ISSUE TITLE
Set a log Level

### ISSUE THREAD

**Issue by SantoDE** [containous/traefik-helm-chart#189]
Currently, the only way to define a `logLevel` the helm chart is to use the additionalArguments like that `--logs.level=DEBUG`

We can hide that behind a helm configuration to enforce that for the user automatically

Partially fixes #185

**Comment by kgorskowski** [comment]
Hi. Just a question from my side, I've seen this done in other helm charts by setting environment variables. So is the TRAEFIK_LOG_LEVEL respected in the helm deployment? If this is the case this could be a quick fix by just introducing eg a logLevel value and using that as an env in the pod? correct me if I am wrong in any part of my reasoning :)
