### ISSUE TITLE
feat: Add Support For Sidecar Container

### ISSUE THREAD

**Issue by crhuber** [containous/traefik-helm-chart#19]
It would be great if one could define a second container to run alongside traefik as a sidecar. For example this could be used to setup ForwardAuth to send traffic to a sidecar for JWT authentication

**Comment by mmatur** [comment]
@crhuber Thanks for the proposition. 

I'm not sure this is something we want to introduce in the helm chart. 

There is multi other solution to solve this type of issue. 

So I'm closing this issue

**Comment by strophy** [comment]
@mmatur could you give a few keywords on details of these multiple other solutions please, to help beginners out? I'm trying to add a Tailscale sidecar to Traefik for example, how would I go about this if Traefik is installed using the Helm chart?

**Comment by strophy** [comment]
OK, it seems it is now possible to use `deployment.additionalContainers` and `deployment.initContainers` to specify a sidecar containers. With Kubernetes 1.29+ [native sidecar functionality](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/) is enabled by specifying `restartPolicy: Always` in an init container.
