### ISSUE TITLE
how to make two traefik ingress controller work in same kubernetes cluster in different namespace?

### ISSUE THREAD

**Issue by zeroone-shreeram** [containous/traefik-helm-chart#210]
i tried installing two traefik ingress controller in the same k8s cluster but while browsing the URL got some conflicts. (bas gateway issues, broken web pages)

also tied adding additional args while depoying helm chart
```
helm install traefik-test traefik/traefik -n traefik-test --set="additionalArguments={--providers.kubernetescrd.ingressclass=traefik-test,--providers.kubernetesingress.ingressclass=traefik-test,--entrypoints.web.http.redirections.entrypoint.to=:443,--entrypoints.web.http.redirections.entrypoint.permanent=true}"
```
and added kubernetes.io/ingress.class: traefik-test annotation in ingress manifests but it didnot fix the issue.

how can i use two traefik ingress controller in same kubernetes cluster in different namespace without any conflicts?

**Comment by SantoDE** [comment]
Hello,

questions like that are best answered in our community forum:

https://community.containo.us/c/traefik/traefik-v2/10

Best is to head over there and ask your question there :-)
