### ISSUE TITLE
helm update

### ISSUE THREAD

**Issue by ekjuanrejon** [containous/traefik-helm-chart#22]
Helm update does not seem to update the ingressroute

**Comment by dtomcej** [comment]
This is due to the ingressRoute being created via Hook.

We could modify the hook to post-update too I suppose.

Thoughts @dduportal ?

**Comment by brandond** [comment]
I just got caught by the same issue. Would love to see this resolved.

**Comment by jasperkuperus** [comment]
Although not a solution: considering the default dashboard ingress route doesn't do auth, it's probably a good idea to define the ingress for the dashboard with the appropriate auth yourself. I ended up with this solution.

**Comment by mmatur** [comment]
Fixed by #100
