### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by markxnelson** [containous/traefik-helm-chart#222]
Hi,
The helm chart at https://hub.helm.sh/charts/stable/traefik, which seems to be the "official" chart, still uses 1.x.  Is there any timeline for 2.x to be considered "stable"?  Is this chart intended for production use? 
Thanks

**Comment by SantoDE** [comment]
Hey @markxnelson,

this chart is ready for stable usage. It is also available on the helm hub: https://hub.helm.sh/charts/traefik/traefik

The chart you mentioned, is the official "old" helm chart for v1. However, based on helm guidelances the helm-chart for v2 is on that repo here, but also available on the hub as per the link above. I hope it helps!

Bests
