### ISSUE TITLE
Allow ingress only option dashboard 

### ISSUE THREAD

**Issue by DirtyCajunRice** [containous/traefik-helm-chart#237]
As version 2.2 has re-allowed native ingress, allow creating a kube native ingress vs a ingressroute for the dashboard

Maybe as a switch...
```
dashboard:
  type: ingressroute # options are ingress / ingressroute
```

**Comment by SantoDE** [comment]
With the Ingress, its a bit more tricky as its not as feature rich as the Ingress Route. For example, you'd need another K8s Service Object for the dashboard, rather then the "internal" one we can use with the IngressRoute. I dont think we will add it for that reason to be honest.

Having one way seems sufficent to me?

**Comment by DirtyCajunRice** [comment]
My request in the main repo was just shot down. I Assumed the goal for ingress was feature parity but it seems not. Ill close this out and re open if yall change directoon
