### ISSUE TITLE
RBAC missing PCV

### ISSUE THREAD

**Issue by fireba11** [containous/traefik-helm-chart#255]
If you try to use a PCV to store your LE certificates you'll notice that the permission needed for a PVC is not included in the RBAC.

**Comment by mmatur** [comment]
Hi @fireba11,

Traefik does not need permission to list, get, watch, create or update PVC. For which reason you should have these permissions?

**Comment by fireba11** [comment]
if you use what is prepared from values.yml you need a pvc ...

# Enable persistence using Persistent Volume Claims
# ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
# After the pvc has been mounted, add the configs into traefik by using the `additionalArguments` list below, eg:
# additionalArguments:
# - "--certificatesresolvers.le.acme.storage=/data/acme.json"
# It will persist TLS certificates.
persistence:
  enabled: false
#  existingClaim: ""
  accessMode: ReadWriteOnce
  size: 128Mi
  # storageClass: ""
  path: /data
  annotations: {}
  # subPath: "" # only mount a subpath of the Volume into the pod

**Comment by mmatur** [comment]
The created RBAC is only for traefik instance. Your account need to have the right to manage PVC but traefik does not need this right.

**Comment by fireba11** [comment]
Since this is an option in the values.yml i would expect the chart to extend the RBAC if i enable persistence ...
if not that example should not be in there.
