### ISSUE TITLE
Persistent volume claim

### ISSUE THREAD

**Issue by ekjuanrejon** [containous/traefik-helm-chart#40]
Can the chart be updated to use PVC to store the certs. right now every time the pod restarts it has to get certs from lets encrypt

**Comment by dtomcej** [comment]
Doing this would limit your replicas to 1.

Not sure that is the correct thing to do.

**Comment by Mokto** [comment]
Or you use a PVC that works with ReadWriteMany.

Like EFS.

**Comment by ekjuanrejon** [comment]
Okay. Am just concerned that while updating the arguments restarts the pod and might hit lets encrypt rate limit? How to avoid that?

**Comment by sennerholm** [comment]
If you have an PVC you maybe should convert it to a statefulset so it's not depending on having a readwritemany storage?

But is the certificates really fetched from lets encrypt? Aren't they stored in the secret created by cert-manager?

**Comment by mmatur** [comment]
Fixed by #86
