### ISSUE TITLE
Add annotations if Prometheus is enabled

### ISSUE THREAD

**Issue by valerauko** [containous/traefik-helm-chart#46]
In the current (stable/traefik) helm chart, even if Prometheus metrics are enabled, the relevant annotations (prometheus.io/scrape etc) don't get added to the Deployment. I think it'd be much more user-friendly if those annotations were added automatically.

I know that this is a repo for the traefik 2 chart, but I couldn't figure a better place to open the issue.

**Comment by jpmckearin** [comment]
@valerauko this is the place you are looking for https://github.com/helm/charts/issues/new/choose, select "Get Started" beside "Feature Request"

**Comment by holmesb** [comment]
Why is this closed?  It isn't merged into this chart.
