### ISSUE TITLE
Horizontal Pod Autoscaler

### ISSUE THREAD

**Issue by amalucelli** [containous/traefik-helm-chart#48]
In the current specification, the HPA isn't enabled, allowing only the value of replicas to be changed.

Is there a plan to support this kind of scaling based on CPU and/or memory as is done in the previous version?

https://github.com/helm/charts/blob/master/stable/traefik/values.yaml#L482-L493

I can port this to this chart if that is the plan.

**Comment by dtomcej** [comment]
Closed by #126
