### ISSUE TITLE
Traefik 3.x Helm Chart

### ISSUE THREAD

**Issue by jsmith-dev** [containous/traefik-helm-chart#73]
### Do you want to request a *feature* or report a *bug*?

Install Feature : Helm 3.x Install Chart 

### What did you expect to see?

I am deploying to k3s - and that Kubernetes Distro from Rancher has now moved to Helm 3 charts.

Would it be possible to expedite the development of a Helm 3 chart for Traefik so that K3S may move forward in picking up Traefik 2 (and migrating from Traefik 1.x) either as an option or well documented manual custom process.

Fresh installing K3S --without-traefik AND downgrading Helm to V2 is more hacking than is ideal.

**Comment by jimmycuadra** [comment]
I'm curious what problems there are if we install the current charts using Helm 3. I just tried deploying the chart from this repository (as of commit 76cc1a80eefe0a00d17c2c5c71340cead1bad22e) using Helm 3.0.3 to a test k8s cluster and it seems to work. 🤷‍♂

**Comment by dtomcej** [comment]
There shouldn't be any issues outside of the CRD management mentioned above.

We should probably get this going since Helm v3 is now stable and the de facto standard.
