### ISSUE TITLE
[Feature] Be able to add many traefik ingress

### ISSUE THREAD

**Issue by Nainterceptor** [containous/traefik-helm-chart#75]
Hello,

I've tried to install two times the ingress, one time per namespace on a cluster, but, second time, crd are already exists, so helm 3 return an error.
Maybe is it possible to wrap crd into a condition to be able to ignore crd setup ?
In the idea, on a cluster, I want to scope two teams in their respective namespaces.

Best regards !
Gaël

**Comment by mmatur** [comment]
Hi @Nainterceptor ,

Since the PR #94 crds are created only one time.

```bash
kubectl create ns traefik-1
helm install --namespace=traefik-1 traefik-1 traefik/traefik
kubectl create ns traefik-2
helm install --namespace=traefik-2 traefik-2 traefik/traefik
```
