### ISSUE TITLE
Helm delete does not remove everything

### ISSUE THREAD

**Issue by cstack89** [containous/traefik-helm-chart#77]
Versions
Helm:  2.8.2
Kubernetes:  1.17.2
OS: Ubuntu 18.04

I'm new to pretty much all the technologies involved here, so forgive me if I'm missing something obvious. But I've been trying to get Traefik 2.1 setup using this helm chart by running:
`helm install --replace --name traefik21 ./traefik-helm-chart/traefik/ --values traefik-chart2.yml`

Since I have no idea what I'm doing... I've also been removing it a lot. I assume that when I do `helm delete traefik21` it should delete everything but it does not. In fact I'm not sure what if anything it removes. Usually I then run `kubectl delete deploy traefik21` and then install again.

Is there a better way to do this?

Also in general if I have other questions (why can't I access the dashboard, why are my certs wrong, etc.). Should I open other tickets here, on the main traefik github site, or somewhere else?

**Comment by etschelp** [comment]
Concerning your first question, i was struggling with that as well. I resolved it like this:
`helm list`
This will return the generated name of the chart, e.g. traefik-1580902682, then you can run
`helm uninstall  traefik-1580902682`
The next issue is that this will leave all the resource definitions, so you have to clean them manually for each file you fine within ./traefik-helm-chart/traefik/templates/crd e.g.
`kubectl delete -f ./traefik-helm-chart/traefik/templates/crd/ingressroute.yaml`

Concerning your other questions. The dashboard port is not exposed per default, but you can change this in the values.yml.  Also traefik is not configured when you  install it with helm, you will either have to set environment properties (also in the values.yml) or add arguments during helm install like:

`helm install ./traefik-helm-chart/traefik --set="{--providers.kubernetesingress=true,--global.checknewversion=true,--entryPoints.web.address=:80,--entryPoints.websecure.address=:443}"`

I did the install with helm 3

**Comment by cstack89** [comment]
Thanks for the help, I've finally started getting to the point where I'm not adding and removing things as much. Are the CRDs left for any reason in particular?

I ended up making separate files for ingressroutes, middleware, etc and just treated the helm install as a baselayer. That seems to be working ok for me.

**Comment by mmatur** [comment]
I am closing this issue because I think that the question is answered.

Thanks for your contribution
