### ISSUE TITLE
Security concern: API/Dashboard should not be exposed on entry "web" by default

### ISSUE THREAD

**Issue by nanmu42** [containous/traefik-helm-chart#78]
Hi, Traefik API/dashboard is turned on and exposed on entry `web` by default, which is kind of scary, since the whole Internet may access them.

https://github.com/containous/traefik-helm-chart/blob/76cc1a80eefe0a00d17c2c5c71340cead1bad22e/traefik/templates/dashboard-hook-ingressroute.yaml#L13-L21

I propose to expose them on entry `treafik` to avoid bad things happen.

https://github.com/containous/traefik-helm-chart/blob/76cc1a80eefe0a00d17c2c5c71340cead1bad22e/traefik/values.yaml#L35-L45

I would like to draft a small PR if you guys consider it a good idea.

Brilliant work. I am enjoying it. Thank you.

**Comment by ldez** [comment]
Hello,

by default the IngressRoute for the Dashboard is disabled:
https://github.com/containous/traefik-helm-chart/blob/76cc1a80eefe0a00d17c2c5c71340cead1bad22e/traefik/values.yaml#L79

This IngressRoute it's just an optional helper, mainly for testing purpose, to activate the dashboard: in production and in all cases you have to create an IngressRoute manually to add TLS, auth, ...
