### ISSUE TITLE
Add parameter to set basic auth secret to access dashboard

### ISSUE THREAD

**Issue by myco** [containous/traefik-helm-chart#88]
I couldn't find a way to set basic auth secret to access dashboard.
In old version it was done by dashboard.auth.basic

**Comment by thomascraig** [comment]
@myco you have to add a middleware for the auth and call the middleware via your router

**Comment by mmatur** [comment]
Hi,

The dashboard is not more exposed by default. So it is secure by default. 

We want to keep the chart as simple as possible.

So if you want to expose your dashboard and enable the auth you should follow the instruction [here](https://docs.traefik.io/operations/dashboard/#secure-mode)
