### ISSUE TITLE
New bug fix release needed after tracing OpenTelemetry addition bug which was fixed after release.

### ISSUE THREAD

**Issue by gcaracuel** [containous/traefik-helm-chart#904]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik-helm-chart/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What version of the Traefik's Helm Chart are you using?

v23.2.0

### What version of Traefik are you using?

v3.0

### What did you do?

Next commit was introduced after last release https://github.com/traefik/traefik-helm-chart/commit/571b36aeaf3f6b136f0b3c210a29e3c8d5661acd

This commit fixes Opentelemetry config when no TLS is configured. Without this the render just crash if no TLS config provided. A bugfix release needs to be created with that commit included.

### What did you see instead?

```
Error: template: traefik/templates/_podtemplate.tpl:377:24: executing "traefik.podTemplate" at <.Values.tracing.openTelemetry.tls.ca>: nil pointer evaluating interface {}.ca
```

When config looks like:
```
tracing:
  openTelemetry:
    address: otlp:4317
    grpc: {}
    insecure: true
```

### What is your environment & configuration?

Mentioned above

**Comment by mloiseleur** [comment]
Yes, you're right. 
There is a breaking change, so it will need a major version bump.

**Comment by gcaracuel** [comment]
Thanks!
